/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'nickname' : string,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface DuelResult {
  'id' : string,
  'matchedAt' : [] | [bigint],
  'expiresAt' : bigint,
  'challengerNickname' : string,
  'winnerId' : [] | [Principal],
  'opponentNickname' : [] | [string],
  'opponentScore' : [] | [bigint],
  'createdAt' : bigint,
  'state' : DuelState,
  'challengerScore' : [] | [bigint],
  'amount' : bigint,
  'challenger' : Principal,
  'opponent' : [] | [Principal],
}
export type DuelState = { 'resolved' : null } |
  { 'expired' : null } |
  { 'opponent_played' : null } |
  { 'open' : null } |
  { 'matched' : null } |
  { 'challenger_played' : null };
export interface LeaderboardEntry {
  'principal' : Principal,
  'nickname' : string,
  'rank' : bigint,
  'score' : bigint,
  'shareCount' : bigint,
  'timestamp' : bigint,
}
export interface ScoreEntry {
  'principal' : Principal,
  'nickname' : string,
  'score' : bigint,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'acceptDuelChallenge' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminDeleteChatMessage' : ActorMethod<[bigint, string], undefined>,
  'adminInsertScore' : ActorMethod<[string, string, bigint], undefined>,
  'adminResetWeeklyLeaderboard' : ActorMethod<[string], undefined>,
  'adminSetTournamentStart' : ActorMethod<[string, bigint], undefined>,
  'adminSetWeeklyResetTime' : ActorMethod<[string, bigint], undefined>,
  'changeNickname' : ActorMethod<[string], undefined>,
  'deleteOwnChatMessage' : ActorMethod<[bigint], undefined>,
  'expireOldDuels' : ActorMethod<[], undefined>,
  'getAllScores' : ActorMethod<[], Array<ScoreEntry>>,
  'getAllTimeLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getBittyBalance' : ActorMethod<[Principal], bigint>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getDuelHistory' : ActorMethod<[], Array<DuelResult>>,
  'getIcpBalance' : ActorMethod<[Principal], bigint>,
  'getMyDuels' : ActorMethod<[], Array<DuelResult>>,
  'getMyNickname' : ActorMethod<[], [] | [string]>,
  'getOpenDuels' : ActorMethod<[], Array<DuelResult>>,
  'getTopScores' : ActorMethod<[], Array<ScoreEntry>>,
  'getTopScoresForUser' : ActorMethod<[Principal], Array<ScoreEntry>>,
  'getWeeklyLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'isNicknameAvailable' : ActorMethod<[string], boolean>,
  'playDuel' : ActorMethod<
    [string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'postDuelChallenge' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'recordShare' : ActorMethod<[], undefined>,
  'registerNickname' : ActorMethod<[string], undefined>,
  'sendChatMessage' : ActorMethod<[string], undefined>,
  'submitScore' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];