/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreEntry = IDL.Record({
  'principal' : IDL.Principal,
  'nickname' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'nickname' : IDL.Text,
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
  'shareCount' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'nickname' : IDL.Text,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const DuelState = IDL.Variant({
  'resolved' : IDL.Null,
  'expired' : IDL.Null,
  'opponent_played' : IDL.Null,
  'open' : IDL.Null,
  'matched' : IDL.Null,
  'challenger_played' : IDL.Null,
});
export const DuelResult = IDL.Record({
  'id' : IDL.Text,
  'matchedAt' : IDL.Opt(IDL.Int),
  'expiresAt' : IDL.Int,
  'challengerNickname' : IDL.Text,
  'winnerId' : IDL.Opt(IDL.Principal),
  'opponentNickname' : IDL.Opt(IDL.Text),
  'opponentScore' : IDL.Opt(IDL.Nat),
  'createdAt' : IDL.Int,
  'state' : DuelState,
  'challengerScore' : IDL.Opt(IDL.Nat),
  'amount' : IDL.Nat,
  'challenger' : IDL.Principal,
  'opponent' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  'acceptDuelChallenge' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteChatMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminInsertScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'adminResetWeeklyLeaderboard' : IDL.Func([IDL.Text], [], []),
  'adminSetTournamentStart' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'adminSetWeeklyResetTime' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'changeNickname' : IDL.Func([IDL.Text], [], []),
  'deleteOwnChatMessage' : IDL.Func([IDL.Nat], [], []),
  'expireOldDuels' : IDL.Func([], [], []),
  'getAllScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getAllTimeLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getBittyBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDuelHistory' : IDL.Func([], [IDL.Vec(DuelResult)], ['query']),
  'getIcpBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'getMyDuels' : IDL.Func([], [IDL.Vec(DuelResult)], ['query']),
  'getMyNickname' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getOpenDuels' : IDL.Func([], [IDL.Vec(DuelResult)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getTopScoresForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ScoreEntry)],
      ['query'],
    ),
  'getWeeklyLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'isNicknameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'playDuel' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'postDuelChallenge' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'recordShare' : IDL.Func([], [], []),
  'registerNickname' : IDL.Func([IDL.Text], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text], [], []),
  'submitScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreEntry = IDL.Record({
    'principal' : IDL.Principal,
    'nickname' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'nickname' : IDL.Text,
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
    'shareCount' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'nickname' : IDL.Text,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const DuelState = IDL.Variant({
    'resolved' : IDL.Null,
    'expired' : IDL.Null,
    'opponent_played' : IDL.Null,
    'open' : IDL.Null,
    'matched' : IDL.Null,
    'challenger_played' : IDL.Null,
  });
  const DuelResult = IDL.Record({
    'id' : IDL.Text,
    'matchedAt' : IDL.Opt(IDL.Int),
    'expiresAt' : IDL.Int,
    'challengerNickname' : IDL.Text,
    'winnerId' : IDL.Opt(IDL.Principal),
    'opponentNickname' : IDL.Opt(IDL.Text),
    'opponentScore' : IDL.Opt(IDL.Nat),
    'createdAt' : IDL.Int,
    'state' : DuelState,
    'challengerScore' : IDL.Opt(IDL.Nat),
    'amount' : IDL.Nat,
    'challenger' : IDL.Principal,
    'opponent' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    'acceptDuelChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteChatMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminInsertScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'adminResetWeeklyLeaderboard' : IDL.Func([IDL.Text], [], []),
    'adminSetTournamentStart' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'adminSetWeeklyResetTime' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'changeNickname' : IDL.Func([IDL.Text], [], []),
    'deleteOwnChatMessage' : IDL.Func([IDL.Nat], [], []),
    'expireOldDuels' : IDL.Func([], [], []),
    'getAllScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getAllTimeLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getBittyBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDuelHistory' : IDL.Func([], [IDL.Vec(DuelResult)], ['query']),
    'getIcpBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'getMyDuels' : IDL.Func([], [IDL.Vec(DuelResult)], ['query']),
    'getMyNickname' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getOpenDuels' : IDL.Func([], [IDL.Vec(DuelResult)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getTopScoresForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ScoreEntry)],
        ['query'],
      ),
    'getWeeklyLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'isNicknameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'playDuel' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'postDuelChallenge' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'recordShare' : IDL.Func([], [], []),
    'registerNickname' : IDL.Func([IDL.Text], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text], [], []),
    'submitScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };