/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    principal: Principal;
    nickname: string;
    rank: bigint;
    score: bigint;
    shareCount: bigint;
    timestamp: bigint;
}
export interface ChatMessage {
    id: bigint;
    nickname: string;
    text: string;
    author: Principal;
    timestamp: bigint;
}
export interface DuelResult {
    id: string;
    matchedAt?: bigint;
    expiresAt: bigint;
    challengerNickname: string;
    winnerId?: Principal;
    opponentNickname?: string;
    opponentScore?: bigint;
    createdAt: bigint;
    state: DuelState;
    challengerScore?: bigint;
    amount: bigint;
    challenger: Principal;
    opponent?: Principal;
}
export interface ScoreEntry {
    principal: Principal;
    nickname: string;
    score: bigint;
    timestamp: bigint;
}
export enum DuelState {
    resolved = "resolved",
    expired = "expired",
    opponent_played = "opponent_played",
    open = "open",
    matched = "matched",
    challenger_played = "challenger_played"
}
export interface backendInterface {
    acceptDuelChallenge(duelId: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteChatMessage(id: bigint, password: string): Promise<void>;
    adminInsertScore(password: string, nickname: string, score: bigint): Promise<void>;
    adminResetWeeklyLeaderboard(password: string): Promise<void>;
    adminSetTournamentStart(password: string, newTimestampNs: bigint): Promise<void>;
    adminSetWeeklyResetTime(password: string, newTimestampNs: bigint): Promise<void>;
    changeNickname(newNickname: string): Promise<void>;
    deleteOwnChatMessage(id: bigint): Promise<void>;
    expireOldDuels(): Promise<void>;
    getAllScores(): Promise<Array<ScoreEntry>>;
    getAllTimeLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getBittyBalance(owner: Principal): Promise<bigint>;
    getChatMessages(): Promise<Array<ChatMessage>>;
    getDuelHistory(): Promise<Array<DuelResult>>;
    getIcpBalance(owner: Principal): Promise<bigint>;
    getMyDuels(): Promise<Array<DuelResult>>;
    getMyNickname(): Promise<string | null>;
    getOpenDuels(): Promise<Array<DuelResult>>;
    getTopScores(): Promise<Array<ScoreEntry>>;
    getTopScoresForUser(user: Principal): Promise<Array<ScoreEntry>>;
    getWeeklyLeaderboard(): Promise<Array<LeaderboardEntry>>;
    isNicknameAvailable(nickname: string): Promise<boolean>;
    playDuel(duelId: string, score: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    postDuelChallenge(amount: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordShare(): Promise<void>;
    registerNickname(nickname: string): Promise<void>;
    sendChatMessage(text: string): Promise<void>;
    submitScore(score: bigint): Promise<void>;
}
import type { DuelResult as _DuelResult, DuelState as _DuelState } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptDuelChallenge(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptDuelChallenge(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptDuelChallenge(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteChatMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteChatMessage(arg0, arg1);
            return result;
        }
    }
    async adminInsertScore(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminInsertScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminInsertScore(arg0, arg1, arg2);
            return result;
        }
    }
    async adminResetWeeklyLeaderboard(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetWeeklyLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetWeeklyLeaderboard(arg0);
            return result;
        }
    }
    async adminSetTournamentStart(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetTournamentStart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetTournamentStart(arg0, arg1);
            return result;
        }
    }
    async adminSetWeeklyResetTime(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetWeeklyResetTime(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetWeeklyResetTime(arg0, arg1);
            return result;
        }
    }
    async changeNickname(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeNickname(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeNickname(arg0);
            return result;
        }
    }
    async deleteOwnChatMessage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOwnChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOwnChatMessage(arg0);
            return result;
        }
    }
    async expireOldDuels(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.expireOldDuels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.expireOldDuels();
            return result;
        }
    }
    async getAllScores(): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScores();
            return result;
        }
    }
    async getAllTimeLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimeLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimeLeaderboard();
            return result;
        }
    }
    async getBittyBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBittyBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBittyBalance(arg0);
            return result;
        }
    }
    async getChatMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages();
            return result;
        }
    }
    async getDuelHistory(): Promise<Array<DuelResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDuelHistory();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDuelHistory();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIcpBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpBalance(arg0);
            return result;
        }
    }
    async getMyDuels(): Promise<Array<DuelResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDuels();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDuels();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNickname(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNickname();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNickname();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenDuels(): Promise<Array<DuelResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenDuels();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenDuels();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopScores(): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopScores();
            return result;
        }
    }
    async getTopScoresForUser(arg0: Principal): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopScoresForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopScoresForUser(arg0);
            return result;
        }
    }
    async getWeeklyLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyLeaderboard();
            return result;
        }
    }
    async isNicknameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isNicknameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isNicknameAvailable(arg0);
            return result;
        }
    }
    async playDuel(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.playDuel(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.playDuel(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async postDuelChallenge(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.postDuelChallenge(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postDuelChallenge(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordShare(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordShare();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordShare();
            return result;
        }
    }
    async registerNickname(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerNickname(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerNickname(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return result;
        }
    }
    async submitScore(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScore(arg0);
            return result;
        }
    }
}
function from_candid_DuelResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DuelResult): DuelResult {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_DuelState_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DuelState): DuelState {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    matchedAt: [] | [bigint];
    expiresAt: bigint;
    challengerNickname: string;
    winnerId: [] | [Principal];
    opponentNickname: [] | [string];
    opponentScore: [] | [bigint];
    createdAt: bigint;
    state: _DuelState;
    challengerScore: [] | [bigint];
    amount: bigint;
    challenger: Principal;
    opponent: [] | [Principal];
}): {
    id: string;
    matchedAt?: bigint;
    expiresAt: bigint;
    challengerNickname: string;
    winnerId?: Principal;
    opponentNickname?: string;
    opponentScore?: bigint;
    createdAt: bigint;
    state: DuelState;
    challengerScore?: bigint;
    amount: bigint;
    challenger: Principal;
    opponent?: Principal;
} {
    return {
        id: value.id,
        matchedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.matchedAt)),
        expiresAt: value.expiresAt,
        challengerNickname: value.challengerNickname,
        winnerId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.winnerId)),
        opponentNickname: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.opponentNickname)),
        opponentScore: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.opponentScore)),
        createdAt: value.createdAt,
        state: from_candid_DuelState_n9(_uploadFile, _downloadFile, value.state),
        challengerScore: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.challengerScore)),
        amount: value.amount,
        challenger: value.challenger,
        opponent: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.opponent))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    expired: null;
} | {
    opponent_played: null;
} | {
    open: null;
} | {
    matched: null;
} | {
    challenger_played: null;
}): DuelState {
    return "resolved" in value ? DuelState.resolved : "expired" in value ? DuelState.expired : "opponent_played" in value ? DuelState.opponent_played : "open" in value ? DuelState.open : "matched" in value ? DuelState.matched : "challenger_played" in value ? DuelState.challenger_played : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DuelResult>): Array<DuelResult> {
    return value.map((x)=>from_candid_DuelResult_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
